version: "3.3"

services:
  app:
    container_name: srcbot
    build: .
    command: bash bash.sh
    environment:
      API_ID: 7712824 # Your API HASH from my.telegram.org
      API_HASH: "2d3673e18b462f8032c4eea2f50b9f52" # Your API ID from my.telegram.org
      BOT_TOKEN: "2073401563:AAFOL_jXMsqIhZCVPt2gqE4mrwy0MJTykI0" # Bot token, get it from @BotFather 
      SESSION: "workding" # Pyrogram string session
      AUTH: 1808315958 # User ID of Bot owner
      FORCESUB: # Username name of public channel without using '@'
